language: python
python:
- '3.6'
- '3.6-dev'
- 'nightly'
install:
- pip install -e .
- pip install -r requirements.txt
- pip install coveralls
script: pytest tests
notifications:
  email: false
after_success: coveralls
